import os

class Config:
  SECRET_KEY=os.environ.get('SECRET_KEY')
  SQLALCHEMY_TRACK_MODIFICATIONS=False
  SQLALCHEMY_DATABASE_URI=os.environ.get('DATABASE_URL')
  SQLALCHEMY_ECHO=True
  AWS_ACCESS_KEY_ID=AKIA3GXY6HZVC4DHUJFG
  AWS_SECRET_ACCESS_KEY=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
