"""empty message

Revision ID: 039270967ab9
Revises: dc7e2fd37e4d
Create Date: 2021-03-23 12:10:14.058840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039270967ab9'
down_revision = 'dc7e2fd37e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_image')
    # ### end Alembic commands ###
