"""empty message

Revision ID: 9785010e1823
Revises: ee9e80d77c95
Create Date: 2021-03-19 14:29:06.276465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9785010e1823'
down_revision = 'ee9e80d77c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotsreviewsjoins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spotsreviewsjoins')
    # ### end Alembic commands ###
