"""added unique to title in spots

Revision ID: f61aba0d48da
Revises: 5f901e03f73d
Create Date: 2021-03-19 16:11:07.345232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61aba0d48da'
down_revision = '5f901e03f73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'spots', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spots', type_='unique')
    # ### end Alembic commands ###
