"""update

Revision ID: 5acd5ab209bf
Revises: 238e0b30d7b3
Create Date: 2021-03-23 12:34:48.784967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acd5ab209bf'
down_revision = '238e0b30d7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_image', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_image', type_='foreignkey')
    # ### end Alembic commands ###
